# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170429_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='mes',
            new_name='month',
        ),
    ]
