# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170429_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='anio',
            new_name='year',
        ),
    ]
